[package]
name = "win32_windows"
version = "0.1.0"
authors = ["Øyvind Nordsveen <oyvind.nordsveen@confirmit.com>"]

[dependencies]
winapi = {version = "0.3.5", features=["winuser", "libloaderapi"]}
libc = "0.2.42"

