[package]
name = "wasm-lib"
version = "0.1.0"
authors = ["Øyvind <oyvind.nordsveen@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
game-core = { path = "../game-core" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.24"
